[package]
name = "c_compiler"
version = "0.1.0"
edition = "2024"
authors = ["Ryan Campbell <ryan.campbell4@gmail.com"]

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
nom = "8.0.0"
